# Generated by Django 3.2.14 on 2023-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='nombre_produto',
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre_producto',
            field=models.CharField(default=100, max_length=150, verbose_name='nombre producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recetas',
            name='imagen_receta',
            field=models.ImageField(upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='nombre_receta',
            field=models.CharField(max_length=150, verbose_name='nombre receta'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='pasos_receta',
            field=models.TextField(verbose_name='instrucciones'),
        ),
    ]
