# Generated by Django 3.2.14 on 2023-01-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='cantidad',
            field=models.FloatField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='fkproductos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rct.productos', verbose_name='prodcuto'),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='fkunidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rct.unidadesdemedida', verbose_name='medida'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tiempo_prep_receta',
            field=models.CharField(max_length=50, verbose_name='tiempo'),
        ),
    ]
