# Generated by Django 3.2.14 on 2023-02-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rct', '0003_auto_20230228_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Asunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='msg_content',
            field=models.TextField(verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Para'),
        ),
    ]
