from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from rct.forms import PassResetForm,NewPasswordForm

app_name='rct'
urlpatterns = [
    #PUBLIC
    path('',views.index,name='index'),
    path('recetas',views.recetas,name='recetas'),
    path('mis_recetas/',views.mis_recetas,name='mis_recetas'),
    path('mis_recetas/crear_receta',views.crear_receta,name='crear_receta'),
    path('mis_recetas/editar_receta/<int:id>/',views.editar_receta,name='editar'),
    path('mis_recetas/eliminar_receta/<int:id>/',views.eliminar_receta,name='eliminar'),
    path('mis_recetas/crear_receta/crear_producto',views.crear_producto,name='crear_producto'),
    path('mis_recetas/crear_receta/crear_medida',views.crear_medida,name='crear_medida'),
    path('receta/<int:id>/',views.receta,name='receta'),
    path('receta/<int:parent_id>/editar_ingrediente/<int:id>/',views.editar_ingrediente,name='editar_ingrediente'),
    path('receta/<int:parent_id>/eliminar_ingrediente/<int:id>/',views.eliminar_ingrediente,name='eliminar_ingrediente'),
    path('receta/<int:parent_id>/guardar_receta/',views.guardar_receta,name='guardar_receta'),
    path('receta/<int:parent_id>/borrar_receta/<int:id>/',views.borrar_receta,name='borrar_receta'),
    path('registro',views.registro,name='registro'),
    path('login',views.recetas_login,name='login'),
    path('password_change',views.cambio_contraseña,name='password_change'),
    path('reset_password',auth_views.PasswordResetView.as_view(form_class=PassResetForm,template_name='rct/public/password_reset.html'),name='reset_password'),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name='rct/public/password_reset_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(form_class=NewPasswordForm,template_name='rct/public/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete',auth_views.PasswordResetDoneView.as_view(template_name='rct/public/password_reset_done.html'),name='password_reset_complete'),
    path('logout',auth_views.LogoutView.as_view(template_name='rct/public/index.html'),name='logout'),
    path('contact',views.contact,name='contact'),
    #ADMINISTRACION
    path('administracion',views.index_administracion,name='administracion'),
    path('administracion/perfil/<int:id>/',views.profile_administracion,name='perfil_admin'),
    path('administracion/perfil/<int:id>/editar-perfil',views.edit_profile_administracion,name='editar_perfil_admin'),
    path('administracion/mensajes',views.mensajes_admin,name='mensajes'),
    path('administracion/mensajes/<int:id>',views.mensaje_admin,name='mensaje'),
    path('administracion/mensajes/crear-mensaje',views.crear_mensaje_admin,name='crear_mensaje'),
    path('administracion/mensajes/<int:id>/eliminar-mensaje',views.eliminar_mensaje,name='eliminar_mensaje'),
    path('administracion/mensajes/<int:id>/mensaje-no-leido',views.mensaje_no_leido,name='mensaje_no_leido'),
    path('administracion/usuarios',views.usuarios,name='usuarios'),
    path('administracion/usuarios/<int:id>/editar-usuario/',views.editar_usuarios_admin,name='editar_usuario'),
    path('administracion/usuarios/<int:id>/eliminar-usuario/',views.eliminar_usuarios_admin,name='eliminar_usuario'),
    path('administracion/staff',views.staff,name='staff'),
    path('administracion/recetas',views.recetas_admin,name='recetas_admin'),
    path('administracion/recetas/<int:id>/instrucciones',views.pasos_receta_admin,name='instrucciones_admin'),
    path('administracion/recetas/<int:id>/instrucciones/editar/',views.editar_pasos_receta_admin,name='editar_instrucciones_admin'),
    path('administracion/recetas/crear-receta',views.crear_recetas_admin,name='crear_receta_admin'),
    path('administracion/recetas/editar-receta/<int:id>/',views.editar_recetas_admin,name='editar_receta_admin'),
    path('administracion/recetas/eliminar-receta/<int:id>/',views.eliminar_recetas_admin,name='eliminar_receta_admin'),
    path('administracion/recetas/<int:parent_id>/ingredientes',views.ingredientes_receta_admin,name='ingredientes_receta_admin'),
    path('administracion/recetas/<int:parent_id>/ingredientes/agregar-ingrediente',views.crear_ingredientes_receta_admin,name='agregar_ingrediente_receta'),
    path('administracion/recetas/<int:parent_id>/ingredientes/editar-ingrediente/<int:id>/',views.editar_ingredientes_receta_admin,name='editar_ingrediente_receta'),
    path('administracion/recetas/<int:parent_id>/ingredientes/eliminar-ingrediente/<int:id>/',views.eliminar_ingredientes_receta_admin,name='eliminar_ingrediente_receta'),
    path('administracion/ingredientes',views.ingredientes_admin,name='ingredientes_admin'),
    path('administracion/productos',views.productos_admin,name='productos_admin'),
    path('administracion/productos/crear-producto',views.crear_productos_admin,name='crear_prod_admin'),
    path('administracion/productos/editar-producto/<int:id>/',views.editar_productos_admin,name='editar_prod_admin'),
    path('administracion/productos/eliminar-producto/<int:id>/',views.eliminar_productos_admin,name='eliminar_prod_admin'),
    path('administracion/unidades-medida',views.medidas_admin,name='medidas_admin'),
    path('administracion/unidades-medida/crear-medida',views.crear_medidas_admin,name='crear_med_admin'),
    path('administracion/unidades-medida/editar-medida/<int:id>/',views.editar_medidas_admin,name='editar_med_admin'),
    path('administracion/unidades-medida/eliminar-medida/<int:id>/',views.eliminar_medidas_admin,name='eliminar_med_admin'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)